name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install 
      - name: Electron Build
        uses: knicknic/os-specific-run@v1.0.3
        with:
          macos: npm run electron-pack
          linux: npm run electron-pack -c.snap.publish=github
          windows: npm run electron-pack
          github_token: ${{ secrets.github_token }
        env:
            # GitHub token, automatically provided to the action
            # (No need to define this secret in the repo settings)
            GITHUB_TOKEN: ${{ secrets.github_token }}

            # If the commit is tagged with a version (e.g. "v1.0.0"),
            # release the app after building
            RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}